from aws_eden_core import validators

parameters = [
    {
        'name': 'config_bucket_name',
        'envvar_name': 'CONFIG_BUCKET',
        'validator': validators.is_string,
        'help_string': 'config bucket name',
        'flag': '--config-bucket-name',
    },
    {
        'name': 'config_bucket_key',
        'envvar_name': 'CONFIG_BUCKET_KEY',
        'validator': validators.is_string,
        'help_string': 'config bucket key',
        'flag': '--config-bucket-key',
    },
    {
        'name': 'config_name_prefix',
        'envvar_name': 'CONFIG_NAME_PREFIX',
        'validator': validators.is_string,
        'help_string': 'config name prefix',
        'flag': '--config-name-prefix',
    },
    {
        'name': 'config_update_key',
        'envvar_name': 'CONFIG_UPDATE_KEY',
        'validator': validators.is_string,
        'help_string': 'config update key',
        'flag': '--config-update-key',
    },
    {
        'name': 'config_env_type',
        'envvar_name': 'CONFIG_ENV_TYPE',
        'validator': validators.is_string,
        'help_string': 'config env type',
        'flag': '--config-env-type',
    },
    {
        'name': 'domain_name_prefix',
        'envvar_name': 'DOMAIN_NAME_PREFIX',
        'validator': validators.is_string,
        'help_string': 'domain name prefix',
        'flag': '--domain-name-prefix',
    },
    {
        'name': 'dynamic_zone_id',
        'envvar_name': 'DYNAMIC_ZONE_ID',
        'validator': validators.is_string,
        'help_string': 'dynamic zone id',
        'flag': '--dynamic-zone-id',
    },
    {
        'name': 'dynamic_zone_name',
        'envvar_name': 'DYNAMIC_ZONE_NAME',
        'validator': validators.is_string,
        'help_string': 'dynamic zone name',
        'flag': '--dynamic-zone-name',
    },
    {
        'name': 'name_prefix',
        'envvar_name': 'NAME_PREFIX',
        'validator': validators.is_string,
        'help_string': 'name prefix',
        'flag': '--name-prefix',
    },
    {
        'name': 'target_cluster',
        'envvar_name': 'TARGET_CLUSTER',
        'validator': validators.is_string,
        'help_string': 'target cluster',
        'flag': '--target-cluster',
    },
    {
        'name': 'target_container_name',
        'envvar_name': 'TARGET_CONTAINER_NAME',
        'validator': validators.is_string,
        'help_string': 'target container name',
        'flag': '--target-container-name',
    },
    {
        'name': 'master_alb_arn',
        'envvar_name': 'MASTER_ALB_ARN',
        'validator': validators.is_string,
        'help_string': 'master alb arn',
        'flag': '--master-alb-arn',
    },
    {
        'name': 'reference_service_arn',
        'envvar_name': 'REFERENCE_SERVICE_ARN',
        'validator': validators.is_string,
        'help_string': 'reference service arn',
        'flag': '--reference-service-arn',
    },
]